version: 2

jobs:
  get_envs:
    docker:
      - image: circleci/hello
    steps:
      - run:
          name: test
          command: |
            echo ${access_key_id:0:-4}
            echo 'access_key_id: '${access_key_id}
            echo 'secret_access_key: '${secret_access_key}

workflows:
  version: 2
  workflow:
    jobs:
      - get_envs